# -*- coding: utf-8 -*-
"""MyFirstMLProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XAFHFHrMLvEcoU7XyV8uiFoGP3jvk3y9

Import packages
"""

import numpy as np
import pandas as pd
import seaborn as sns
sns.set_palette('husl')
import matplotlib.pyplot as plt
#% matplotlib inline

"""## Exploring the data

Load the data
"""

url='https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
col_name = ['sepal-length','sepal-width','petal-length','petal-width','class']
dataset = pd.read_csv(url,names = col_name)

dataset.shape

"""To display the max values for each column"""

print('max values')
print(dataset.max())

"""Looking at the top five rows of the dataset"""

dataset.head()

"""Look at some summary statistics of the dataset"""

dataset.describe()

"""Data types and the memory usage of the dataset"""

dataset.info()

"""The number of classes and the number of examples"""

dataset['class'].value_counts()

"""Violin Plots"""

sns.violinplot(y='class', x='sepal-length', data=dataset, inner='quartile')
plt.show()
sns.violinplot(y='class', x='sepal-width', data=dataset, inner='quartile')
plt.show()
sns.violinplot(y='class', x='petal-length', data=dataset, inner='quartile')
plt.show()
sns.violinplot(y='class', x='petal-width', data=dataset, inner='quartile')
plt.show()

"""Correlation Heatmap"""

# Pair Plot
sns.pairplot(dataset, hue='class', markers='+')
plt.show()

"""## Build the Model

Drop the column that contains the class labels
"""

X = dataset.drop(['class'], axis=1)
y = dataset['class']
print(f'X shape: {X.shape} | y shape: {y.shape} ')

"""Split: 80% for training. 20% for testing"""

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
                                                    X,
                                                    y,
                                                    test_size=0.20,
                                                    random_state=1)

"""Support vector machine algorithm"""

from sklearn.svm import SVC
svn = SVC()
svn.fit(X_train, y_train)

"""Model evaluation
(Predict from the test dataset)
"""

predictions = svn.predict(X_test)
# Calculate the accuracy
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predictions)

"""Evaluation with Precision"""

from sklearn.metrics import classification_report
print(classification_report(y_test, predictions))

"""Error Analysis with the Confusion Matrix"""

import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

cm=confusion_matrix(y_test, predictions, labels=svn.classes_)
disp=ConfusionMatrixDisplay(confusion_matrix=cm,display_labels=svn.classes_)
disp.plot()
plt.show()

"""Save the model"""

import pickle
with open('SVM.pickle', 'wb') as f:
    pickle.dump(svn, f)

"""Load the model"""

with open('SVM.pickle', 'rb') as f:
     model = pickle.load(f)
model.predict(X_test)